---
title: "lsvApply"
author: "LEE SANGIN"
date: "2017년 1월 12일"
output: html_document
---

#### lapply : list나 vector로 되어있는 개체의 원소 하나하나에 함수 적용
```{r}
## 항상 list를 반환함
cities <- c("New York","Paris","London","Tokyo","Rio de Janeiro","Cape Town")
lapply(cities, nchar)

##list 가 아닌 vector 형태로 바꾸려면 -> unlist()
unlist(lapply(cities,nchar))

##example
oil_price <- c(2.37,2.49,2.18,2.22,2.47,2.32)
triple <- function(x){
  x*3
}
result <- lapply(oil_price,triple)
#결과
str(result)
unlist(result)

##example2
oil_price <- c(2.37,2.49,2.18,2.22,2.47,2.32)
multiply <- function(x,factor){
  x*factor
}
result2 <- lapply(oil_price,multiply,factor =3)
result3 <- lapply(oil_price,factor=3 , multiply)
#결과
str(result2)
unlist(result2)
unlist(result3)
```

#### sapply : lapply를 단순화(vector)하려고 함. 단순화가 안되면 lapply와 동일한 결과값 출력
```{r}
## 함수를 적용한 개체와 함께 결과값을 반환함(vector)
cities <- c("New York","Paris","London","Tokyo","Rio de Janeiro","Cape Town")
result <- sapply(cities, nchar)

#결과 
result #vector (여기에서는 이름이 나왔지만 데이터 종류에 따라 이름이 안나올 수도 있음)
is.list(result)
is.vector(result)

## 이름을 보이지 않게 하려면
sapply(cities,nchar,USE.NAMES = FALSE)


##function이 여러값을 반환할때
first_and_last <- function(name){ #알파벳을 순서대로 나열하여 처음,끝 출력
  name <- gsub(" ","",name)
  letters <- strsplit(name,split="")[[1]]
  c(first = min(letters),last = max(letters))
}

#결과
first_and_last("New York")

test <- sapply(cities,first_and_last) #matrix
test
is.matrix(test)
is.vector(test)
is.list(test)

##sapply는 lapply를 단순화하는 것이 아니라 이름을 붙이는 것임
##example
unique_letters <- function(name){ #중복 알파벳 제거
  name <- gsub(" ","",name)
  letters <- strsplit(name,split="")[[1]]
  unique(letters)
}

#결과
test <- sapply(cities,unique_letters)
test
is.list(test)
# 여기에서는 개체들의 결과의 갯수가 다 다르므로 vector가 아니라 list, datacamp에서는 이걸 해결 못한다고 함
```

#### vapply(개체,함수,결과값type(갯수)) 
* 안전한 sapply, 결과값 type이 무엇인지, 갯수가 몇개인지 지정해주니 다른 값이 들어올 수 없음
```{r}
## 함수를 적용한 개체와 함께 결과값을 반환함(vector)
cities <- c("New York","Paris","London","Tokyo","Rio de Janeiro","Cape Town")
result <- vapply(cities, nchar,numeric(1))
## 결과
result

##function이 여러값을 반환할때
first_and_last <- function(name){ #알파벳을 순서대로 나열하여 처음,끝 출력
  name <- gsub(" ","",name)
  letters <- strsplit(name,split="")[[1]]
  c(first = min(letters),last = max(letters))
}

#결과
test <- vapply(cities,first_and_last,character(2)) #matrix
test
```

